openapi: 3.0.0
servers:
  - description: "SwaggerHub API Auto Mocking"
    url: https://virtserver.swaggerhub.com/VNGRealisatie/api/bemonstering/v1
  - description: "Referentie-implementatie"
    url: https://www.voorbeeldgemeente.nl/api/bemonstering/v1
info:
  title: Bemonstering
  description: ""
  version: "1.0"
  x-imvertor-generator-version: "1.65.4"
  x-yamlCompiler-stylesheets-version: "20211130"
  contact:
    url: www.waterkwaliteit.nl
  license:
    name: European Union Public License, version 1.2 (EUPL-1.2)
    url: https://eupl.eu/1.2/nl/
paths:
  /bemonstering:
    get:
      operationId: Getbemonstering
      description: ""
      responses:
        '200':
          description: "Zoekactie geslaagd"
          headers:
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/warning"
            X-Rate-Limit-Limit:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Limit"
            X-Rate-Limit-Remaining:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Remaining"
            X-Rate-Limit-Reset:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/X_Rate_Limit_Reset"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Bemonstering'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/403"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/default"
      tags: 
      - Bemonstering
    post:
      operationId: postbemonstering
      description: ""
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/Bemonstering'
      responses:
        '201':
          description: "OK"
          headers:
            Location:
              description: "URI van de nieuwe resource"
              schema:
                type: string
                format: uri
                example: '/bemonstering/'
            api-version:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/api_version"
            warning:
              $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/headers/warning"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bemonstering'
        '400':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/400"
        '401':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/401"
        '403':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/403"
        '409':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/409"
        '410':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/410"
        '415':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/415"
        '429':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/429"
        '500':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/500"
        '501':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/501"
        '503':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/503"
        'default':
          $ref: "https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/responses/default"
      tags: 
      - Bemonstering
components:
  schemas:
    Bemonstering:
      type: object
      description: <body><p>Dat deel van de fysieke werkelijkheid dat wordt beschouwd
        of geanalyseerd.</p><p>Monster meetobject en waarneminsproces zijn hierin
        samengevoegd</p></body>
      required:
      - analyses
      - biota
      - geometrie
      - identificatie
      - monsterCompartiment
      properties:
        analyses:
          $ref: '#/components/schemas/AnalyseProces'
        bemonsteringsapparaat:
          type: string
          title: id
          description: '<body><p>Bemonsteringsapparaat. De beschrijving van het soort
            apparaat waarmee de monstername in het veld is uitgevoerd. Domeintabel:
            BemonsteringsApparaat</p></body>'
        biota:
          $ref: '#/components/schemas/Biota'
        geometrie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/common.yaml#/components/schemas/GeoJSONGeometry'
        identificatie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/Generieke-Datatypen-Gemeenten.yaml#/components/schemas/NEN3610ID'
        monsterCompartiment:
          type: string
          title: id
          description: '<body><p>matrix / Soort compartiment waarin het monster is
            genomen. Grond, Grondwater .e.d. Domeintabel: Compartiment</p></body>'
          minLength: 1
    Analyse:
      type: object
      description: <body><p>Analyse Een analyse waarneming, gemeten en bepaald op
        een speciale manier.</p></body>
      required:
      - fysiekeEigenschap
      - identificatie
      - meetresultaat
      - resultaatDatum
      properties:
        begindatum:
          type: string
          title: phenomenontime
          description: <body><p>Start- en eindtijd van een metingen reeks, indien
            het om een reeks gaat en dus AnalysisRange gevuld is.</p></body>
          format: date-time
        fysiekeEigenschap:
          $ref: '#/components/schemas/FysiekeEigenschap'
        identificatie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/Generieke-Datatypen-Gemeenten.yaml#/components/schemas/NEN3610ID'
        meetresultaat:
          $ref: '#/components/schemas/Meetresultaat'
        resultaatDatum:
          type: string
          title: resulttime
          description: <body><p>Resultaat Datum en tijd.</p><p><gml:TimeInstant><br/>
            <gml:timePosition>2003-02-13T12:28-08:00</gml:timePosition><br/> </gml:TimeInstant></p></body>
          format: date-time
    AnalyseProces:
      type: object
      description: <body><p>Analyse proces Het proces dat uitgevoerd is om tot een
        analyse te komen.</p></body>
      required:
      - identificatie
      - metingen
      properties:
        analyseCompartiment:
          type: string
          title: id
          description: '<body><p>Compartiment - het compartiment waarin de analyse
            is uitgevoerd of waarop de rechtstreekse waarneming betrekking heeft.
            Het analysecompartiment kan afwijken van het monstercompartiment, als
            het analysevoorschrift een bewerking op het monster voorschrijft of als
            een waarneming plaatsvindt zonder fysiek monster. Over het algemeen kan
            gesteld worden dat waarnemingen getoetst kunnen worden aan milieukwaliteitsnormen
            die gelden voor het analysecompartiment. Domeintabel: Compartiment</p></body>'
        identificatie:
          $ref: 'https://raw.githubusercontent.com/VNG-Realisatie/API-Kennisbank/master/common/Generieke-Datatypen-Gemeenten.yaml#/components/schemas/NEN3610ID'
        locatieTypeWaardeBepaling:
          type: string
          title: id
          description: '<body><p>Aanduiding van de plaats waar het resultaat bepaald
            is. Domeintabel: LocatieTypeWaardeBepaling De waarde in-situ is default.</p></body>'
        metingen:
          $ref: '#/components/schemas/Analyse'
        waardebepalingsmethode:
          type: string
          title: id
          description: '<body><p>wijze waarop de meetwaarde bepaald is Domeintabel:
            Waardebepalingsmethode</p></body>'
    Biota:
      type: object
      description: <body><p>Speciaal datatype voor uitbreidingen aan het monster voor
        de biota kenmerken voor bio-monsters.</p></body>
      properties:
        orgaan:
          type: string
          title: id
          description: '<body><p>Soort orgaan. Domeintabel: Orgaan</p></body>'
        organisme:
          type: string
          title: id
          description: '<body><p>organisme - Nadere aanduiding van het organisme waarin
            het monster is genomen. Domeintabel: Biotaxon</p></body>'
    FysiekeEigenschap:
      type: object
      description: '<body><p>PhysicalProperty - Is een (fysieke) eigenschap van een
        object die kan worden gemeten of waargenomen.</p><p>Physical Property is een
        samengesteld attribuut bestaand uit:<br/> • een grootheid (domeintabel Parameter,
        groep Grootheid) plus evt. • een parameter (domeintabel Parameter, groep
        ChemischeStof/groep Object) of domeintabel Biotaxon) en/of • één of meerdere
        hoedanigheden (domeintabel Hoedanigheid).</p><p>Voorbeelden hiervan zijn:</p><p>Grootheid
        (domeintabel Parameter, groep Grootheid): Aantal Parameter (domeintabel Parameter,
        groep Object): Badgast</p><p>Grootheid (domeintabel Parameter, groep Grootheid):
        Waterhoogte Hoedanigheid (domeintabel Hoedanigheid): t.o.v. NAP</p><p>Grootheid
        (domeintabel Parameter, groep Grootheid): (massa)Concentratie Parameter (domeintabel
        Parameter, groep ChemischeStof): lood Hoedanigheid (domeintabel Hoedanigheid):
        t.o.v. drooggewicht</p></body>'
      required:
      - biotaxon
      - quantity
      properties:
        biotaxon:
          type: string
          title: id
          description: ""
          minLength: 1
        hoedanigheid:
          type: array
          title: id
          description: '<body><p>Hoedanigheid (Filtratie, Drooggewicht, Korrelfractiegroottes)
            Domeintabel: Hoedanigheid</p></body>'
          minItems: 0
          items:
            type: string
        parameter:
          type: string
          title: id
          description: '<body><p>Physical Property: Parameter (ChemischeStof: lood
            Object: Badgast) Domeintabel: Parameter biotaxon</p></body>'
        quantity:
          type: string
          title: id
          description: '<body><p>Grootheid (Aantal, Concentratie, Dikte, Temperatuur,
            pH) Domeintabel: Parameter (in de groep: Grootheid)</p></body>'
          minLength: 1
    Meetresultaat:
      type: object
      description: <body><p>Meetresultaat. De uitkomst van een meting in de vorm van
        een numerieke waarde.</p></body>
      required:
      - eenheid
      properties:
        alphanumericvalue:
          type: string
          title: alphanumericvalue
          description: <body><p>Textuele waarde bij een analyse resultaat</p></body>
        eenheid:
          type: string
          title: id
          description: <body><p>Eenheid</p></body>
          minLength: 1
        limitsymbol:
          type: string
          title: limitsymbol
          description: '<body><p>LimietSymbool, toegestane waardes: ''&lt;'' en ''&gt;''.
            ''&lt;'' staat voor ''kleiner dan laagste grenswaarde'' ''&gt;'' staat
            voor ''groter dan hoogste grenswaarde''</p><p>De gehanteerde grens voor
            het limietsymbool kan worden opgegeven in de DeteminationLimits (LimitSymbolReferenceCode)
            als referentie met de daadwerkelijke waarde van de grens. De waarde kan
            op 2 mogelijkheden opgenomen worden in de uitwisseling:1) als CData blok:<br/>
            <![CDATA[<]]> of <![CDATA[>]]> 2) als HTML code: ''&amp; lt;'' of ''&amp;
            gt;''</p></body>'
        numeriekeWaarde:
          type: number
          title: numericvalue
          description: <body><p>Numeriekwaarde - de numerieke waarde van de waarneming.
            Wanneer er geen eenheid bij de meting bekend is, moet de eenheid 'Dimensieloos'
            gebruikt worden.</p></body>
        qualityindicatortype:
          type: string
          title: id
          description: '<body><p>KwaliteitsIndicator/Oordeel -> Detectiegrens e.d.
            Domeintabel: Kwaliteitsoordeel</p></body>'
        valueprocessingmethod:
          type: string
          title: id
          description: '<body><p>waardebewerkingsMethode een wiskundige/statistische
            bewerking die toegepast wordt waarbij de waardebepalingsmethode/analysenorm
            ongewijzigd blijft.</p><p>De bewerking kan worden toegepast op een reeks
            meetwaarden met gelijke parameter (grootheid/component of typering of
            taxon of object) of op een reeks meetwaarden met gelijke analysemethode
            die worden gesommeerd tot een somparameter. Domeintabel: WaardebewerkingsMethode</p></body>'
