
baseurl: "/Waterkwaliteit"
apiname: "Waterkwaliteit"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: Waterkwaliteit-metingen
    subnav:
      - title: Main
        path: /
  - title: Documentatie
    subnav:
  - title: Specificaties in concept
    subnav:
#      - title: Getting started
#        path: /getting-started
#      - title: User stories
#        url: https://vng-realisatie.github.io/IMWOZ-bevragingen/user-stories-prod
#        https://github.com/VNG-Realisatie/IMWOZ-bevragingen/issues?q=is%3Aissue+label%3A%22user+story%22
#        path: /user-stories
      - title: Waterkwaliteit-metingen (swagger-ui)
        path: /WK-swagger-ui
      - title: Waterkwaliteit-metingen (redoc)
        path: /WK-redoc
      - title: Waterkwaliteit-bemonstering A (swagger-ui)
        path: /WKA-swagger-ui
      - title: Waterkwaliteit-metingen A (redoc)
        path: /WKA-redoc
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: JohanBoer/Waterkwaliteit

theme: jekyll-theme-time-machine

project_name: /Waterkwaliteit-metingen
standard_family: Informatiehuis Water
